### ISSUE TITLE
Add support for Lyon edition events

### ISSUE THREAD

**Issue by erkist** [eiffel-community/eiffelevents-sdk-dotnet#2]
### Description
Add support for events part of the Lyon edition of the Eiffel protocol

### Motivation
Most recent protocol edition, likely to be adopted by many users.

### Tasks
- [x] #17 
- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #27
- [x] #28
- [x] #29
- [x] #30
- [x] #31
- [x] #32
- [x] #33
- [x] #34
- [x] #35
- [x] #36
- [x] #37
- [x] #38
- [x] #39
- [x] #40
- [x] #41
- [x] #42
- [x] #43

**Comment by fadykamil** [comment]
Closed
