### ISSUE TITLE
Rename Eiffel RabbitMQ client library

### ISSUE THREAD

**Issue by fadykamil** [eiffel-community/eiffelevents-sdk-dotnet#79]
### Description
Rename client library from `EiffelEvents.RabbitMQ.Client` to `EiffelEvents.Clients.RabbitMQ`

### Motivation
So when we add a client later for e.g. Kafka we can have
`EiffelEvents.Clients.RabbitMq`
`EiffelEvents.Clients.Kafka`
instead of
`EiffelEvents.RabbitMq.Client`
`EiffelEvents.Kafka.Client`

### Benefits
To have a more extensible naming conventions.

**Comment by AhmedAbouElfotouh** [comment]
Merged.
